cur_path="$PWD"
Project/cmake_generic.sh ProjectBuildLinux -DURHO3D_HOME=$cur_path/UrhoBuildLinux -DCMAKE_BUILD_TYPE=Debug -DURHO3D_OPENGL=ON -DURHO3D_SAMPLES=OFF -DURHO3D_C++11=ON -DURHO3D_LIB_TYPE=STATIC -DURHO3D_STATIC_RUNTIME=OFF
